### ISSUE TITLE
Update license files

### ISSUE THREAD

**Issue by agoodm** [philipkershaw/MyProxyClient#3]
Hi @philipkershaw,

Currently I am attempting to upload a conda recipe of MyProxyClient to the conda-forge in this [PR](https://github.com/conda-forge/staged-recipes/pull/1614). The maintainers have requested some clarifications, in particular:
- Is the license BSD or LGPL? It appears to be BSD 3-clause, which would mean the trove classifier needs to be corrected `setup.py`.
- `LICENSE.txt` should be included in `MANIFEST.in`

Let me know if you are able to address these things. If you are too busy, I would be happy to make a PR myself.

**Comment by philipkershaw** [comment]
Good to hear from you.  I am busy so if you can do a pull request that would be great.  Better to do it against:

https://github.com/cedadev/MyProxyClient

The licence is BSD.  Would be good to hear about the kind of things you are using it for.  It's nice to be able to report back to funders.

**Comment by agoodm** [comment]
Our main use for MyProxyClient is for authenticating with the ESGF to download climate data for model evaluation purposes using apache [ocw](https://github.com/apache/climate). Anyway, I will go ahead and submit a PR shortly.

**Comment by philipkershaw** [comment]
Thanks for the PR - Merged into new release 1.4.4 and uploaded to PyPI.

**Comment by agoodm** [comment]
Thanks! We should now be good to upload this package to conda-forge.
