### ISSUE TITLE
certificate generation failure

### ISSUE THREAD

**Issue by dnadeau4** [philipkershaw/MyProxyClient#8]
I have difficulties generating certificates using MyProxyClient.

When installing MyProxyClient from github,  I get the following error:
``` python
>>> from myproxy.client import MyProxyClient
>>> myproxy_clnt = MyProxyClient(hostname="esgf-node.llnl.gov")
>>> cert, private_key = myproxy_clnt.logon('nad****,'*****', bootstrap=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/nadeau1/MyProxyClient/myproxy/client.py", line 1532, in logon
    raise MyProxyClientGetError(errorTxt)

myproxy.client.MyProxyClientGetError: Certificate generation failure.
```

When using the version from "pip install"  it works fine.
```python
>>> from myproxy.client import MyProxyClient
>>> myproxy_clnt = MyProxyClient(hostname="esgf-node.llnl.gov")
>>> cert, private_key = myproxy_clnt.logon('nad****','*****', bootstrap=True)
```

Can you tell me what is different in the latest update?

**Comment by philipkershaw** [comment]
Hello, are you using devel or master on Github and which version are you using from pip.  Please use the issues tracker for cedadev: https://github.com/cedadev/MyProxyClient/issues

Thanks

**Comment by dnadeau4** [comment]
This has been fixed.  Thanks!
